### ISSUE TITLE
checking user rights against null/null/null device does not throw any exception

### ISSUE THREAD

**Issue by Ingvord** [tango-controls/TangoAccessControl#3]
Recently I have encountered the following scenario:

```
DeviceProxyWrapper#executeCommand sys/access_control/1/GetAccess([ingvord, 127.0.0.1, null/null/null])
```

TAC gives `write`. Even though **null/null/null** is a pretty valid Tango device name I would throw an *IllegalArgumentException* in this case.

**Comment by Pascal-Verdier** [comment]
The access control returns Write if you are authorized to write all devices,
Otherwise it returns false.
null/null/null is not an illegal argument. This is a string of 3 fields (device definition).
There is no control if device exists.
